### ISSUE TITLE
Node 14 issue?

### ISSUE THREAD

**Issue by dustinsmith1024** [netlify-labs/netlify-plugin-lighthouse#136]
**Describe the bug**

Should this plugin work when my site is built with Node 14?

**To Reproduce**

1. Add an .nvmrc file to point to Node 14. 
2. Run a deploy

**Expected behavior**

It runs the lighthouse plugin.

**Screenshots**

```

11:57:07 AM: ────────────────────────────────────────────────────────────────
11:57:07 AM:   Netlify Build                                                 
11:57:07 AM: ────────────────────────────────────────────────────────────────
11:57:07 AM: ​
11:57:07 AM: ❯ Version
11:57:07 AM:   @netlify/build 8.0.0
11:57:07 AM: ​
11:57:07 AM: ❯ Flags
11:57:07 AM:   deployId: 5fe0e1a96cf0bc00074c259f
11:57:07 AM:   mode: buildbot
11:57:07 AM: ​
11:57:07 AM: ❯ Current directory
11:57:07 AM:   /opt/build/repo/apps/helpdesk/ui
11:57:07 AM: ​
11:57:07 AM: ❯ Config file
11:57:07 AM:   /opt/build/repo/apps/helpdesk/ui/netlify.toml
11:57:07 AM: ​
11:57:07 AM: ❯ Context
11:57:07 AM:   deploy-preview
11:57:07 AM: ​
11:57:07 AM: ❯ Installing plugins
11:57:07 AM:    - @netlify/plugin-lighthouse@1.4.2
11:57:15 AM: ​
11:57:15 AM: ────────────────────────────────────────────────────────────────
11:57:15 AM:   Core internal error                                           
11:57:15 AM: ────────────────────────────────────────────────────────────────
11:57:15 AM: ​
11:57:15 AM:   Error message
11:57:15 AM:   Error: Cannot find module '@netlify/plugin-lighthouse'
11:57:15 AM:   Require stack:
11:57:15 AM:   - /opt/buildhome/.netlify-build-nvm/versions/node/v12.16.3/lib/node_modules/@netlify/build/src/utils/resolve.js
11:57:15 AM:   - /opt/buildhome/.netlify-build-nvm/versions/node/v12.16.3/lib/node_modules/@netlify/build/src/plugins/resolve.js
11:57:15 AM:   - /opt/buildhome/.netlify-build-nvm/versions/node/v12.16.3/lib/node_modules/@netlify/build/src/plugins/options.js
11:57:15 AM:   - /opt/buildhome/.netlify-build-nvm/versions/node/v12.16.3/lib/node_modules/@netlify/build/src/core/main.js
11:57:15 AM:   - /opt/buildhome/.netlify-build-nvm/versions/node/v12.16.3/lib/node_modules/@netlify/build/src/core/bin.js
11:57:15 AM: ​
11:57:15 AM:   Error location
11:57:15 AM:       at Function.Module._resolveFilename (internal/modules/cjs/loader.js:957:15)
11:57:15 AM:       at Function.resolve (internal/modules/cjs/helpers.js:83:19)
11:57:15 AM:       at resolvePath (/opt/buildhome/.netlify-build-nvm/versions/node/v12.16.3/lib/node_modules/@netlify/build/src/utils/resolve.js:27:22)
11:57:15 AM: ​
11:57:15 AM:   Error properties
11:57:15 AM:   { code: 'MODULE_NOT_FOUND' }
11:57:15 AM: ​
````

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

We are working in a mono repo, but everything is on Node 14. Not sure why it would be attempting to use Node 12.

**Comment by erezrokah** [comment]
Hi @dustinsmith1024, does clearing the build cache help resolve this?

**Comment by erezrokah** [comment]
Closing this issue as stale. Please comment if still relevant
