### ISSUE TITLE
Add incremental logs

### ISSUE THREAD

**Issue by ehmicky** [netlify-labs/netlify-plugin-lighthouse#21]
It seems like some users are canceling builds due to Lighthouse being too slow.

For example [this deploy](https://app.netlify.com/sites/tian-ti/deploys/5ee345c732d6ff0008afde39):

```
11:08:15 AM: ┌──────────────────────────────────────────────────────┐
11:08:15 AM: │ 4. onSuccess command from @netlify/plugin-lighthouse │
11:08:15 AM: └──────────────────────────────────────────────────────┘
11:08:15 AM: ​
11:08:15 AM: Serving and scanning site from directory public
11:08:17 AM:  ⚠  warning (DeprecationWarning)  OutgoingMessage.prototype._headers is deprecated
11:08:17 AM: [DEP0066] 
11:08:17 AM:     at new module.exports (/opt/build/repo/.netlify/plugins/node_modules/union/lib/response-stream.js:50:60)
11:08:17 AM:     at new module.exports (/opt/build/repo/.netlify/plugins/node_modules/union/lib/routing-stream.js:30:17)
11:08:17 AM:     at Server.requestHandler (/opt/build/repo/.netlify/plugins/node_modules/union/lib/core.js:27:25)
11:08:17 AM:     at Server.emit (events.js:310:20)
11:08:17 AM:     at parserOnIncoming (_http_server.js:786:12)
11:08:17 AM:     at HTTPParser.parserOnHeadersComplete (_http_common.js:119:17)
11:09:16 AM: Canceling deploy
11:09:24 AM: ​
11:09:24 AM: ┌────────────────────────────────────────────────────┐
11:09:24 AM: │ Plugin "@netlify/plugin-lighthouse" internal error │
11:09:24 AM: └────────────────────────────────────────────────────┘
11:09:24 AM: ​
11:09:24 AM:   Error message
11:09:24 AM:   UnhandledRejection: a promise was rejected but not handled: LHError: PROTOCOL_TIMEOUT
11:09:24 AM: ​
11:09:24 AM:   Plugin details
11:09:24 AM:   Package:        @netlify/plugin-lighthouse
11:09:24 AM:   Version:        1.1.0
11:09:24 AM:   Repository:     git+https://github.com/netlify-labs/netlify-plugin-lighthouse.git
11:09:24 AM:   npm link:       https://www.npmjs.com/package/@netlify/plugin-lighthouse
11:09:24 AM:   Report issues:  https://github.com/netlify-labs/netlify-plugin-lighthouse/issues
11:09:24 AM: ​
11:09:24 AM:   Error location
11:09:24 AM:   In "onSuccess" event in "@netlify/plugin-lighthouse" from Netlify app
11:09:24 AM:       at Timeout._onTimeout (/opt/build/repo/.netlify/plugins/node_modules/lighthouse/lighthouse-core/gather/driver.js:352:21)
11:09:24 AM:       at listOnTimeout (internal/timers.js:549:17)
11:09:24 AM:       at processTimers (internal/timers.js:492:7)
11:09:24 AM: ​
11:09:24 AM:   Error properties
11:09:24 AM:   {
11:09:24 AM:     code: 'PROTOCOL_TIMEOUT',
11:09:24 AM:     friendlyMessage: 'lighthouse-core/lib/lh-error.js | protocolTimeout # 0',
11:09:24 AM:     lhrRuntimeError: true,
11:09:24 AM:     protocolMethod: 'Runtime.evaluate'
11:09:24 AM:   }
11:09:24 AM: ​
11:09:24 AM:   Resolved config
11:09:24 AM:   build:
11:09:24 AM:     command: hexo generate
11:09:24 AM:     publish: /opt/build/repo/public
11:09:24 AM:   plugins:
11:09:24 AM:     - inputs: {}
11:09:24 AM:       origin: ui
11:09:24 AM:       package: '@netlify/plugin-lighthouse'
11:09:24 AM:     - inputs: {}
11:09:24 AM:       origin: ui
11:09:24 AM:       package: netlify-plugin-gatsby-cache
11:09:24 AM:     - inputs: {}
11:09:24 AM:       origin: ui
11:09:24 AM:       package: netlify-plugin-minify-html
11:09:24 AM: Execution cancelled
11:09:24 AM: Error running command: Command was cancelled
11:09:24 AM: Failing build: Failed to build site
11:09:54 AM: Failed to inform the API about a failed build, please retry the build or contact support
11:09:54 AM: Finished processing build request in 2m32.803437217s
```

Do you think there would be a way to provide with a progress bar to make those users more patient before canceling builds?

**Comment by erezrokah** [comment]
Sure, that makes sense.
I'll look what can be done about that `PROTOCOL_TIMEOUT` error

**Comment by ehmicky** [comment]
Another instance of `PROTOCOL_TIMEOUT`:

```
6:46:58 PM: Build ready to start
6:47:00 PM: build-image version: 30f629161c0736b1a3ecd8b418e5eeffab5c0faf
6:47:00 PM: build-image tag: v3.3.14
6:47:00 PM: buildbot version: 27b83403cb00321ec1f6c83cbc242f21a749fb29
6:47:00 PM: Fetching cached dependencies
6:47:00 PM: Starting to download cache of 205.9MB
6:47:02 PM: Finished downloading cache in 1.687752665s
6:47:02 PM: Starting to extract cache
6:47:07 PM: Finished extracting cache in 4.618438953s
6:47:07 PM: Finished fetching cache in 6.35962166s
6:47:07 PM: Starting to prepare the repo for build
6:47:07 PM: Preparing Git Reference refs/heads/master
6:47:09 PM: Starting build script
6:47:10 PM: Installing dependencies
6:47:10 PM: Started restoring cached node version
6:47:13 PM: Finished restoring cached node version
6:47:14 PM: v10.21.0 is already installed.
6:47:14 PM: Now using node v10.21.0 (npm v6.14.4)
6:47:15 PM: Started restoring cached build plugins
6:47:15 PM: Finished restoring cached build plugins
6:47:15 PM: Attempting ruby version 2.6.2, read from environment
6:47:16 PM: Using ruby version 2.6.2
6:47:16 PM: Using PHP version 5.6
6:47:16 PM: 5.2 is already installed.
6:47:16 PM: Using Swift version 5.2
6:47:16 PM: Started restoring cached go cache
6:47:16 PM: Finished restoring cached go cache
6:47:16 PM: go version go1.12 linux/amd64
6:47:16 PM: go version go1.12 linux/amd64
6:47:16 PM: Installing missing commands
6:47:16 PM: Verify run directory
6:47:18 PM: ​
6:47:18 PM: ┌─────────────────────────────┐
6:47:18 PM: │        Netlify Build        │
6:47:18 PM: └─────────────────────────────┘
6:47:18 PM: ​
6:47:18 PM: ❯ Version
6:47:18 PM:   @netlify/build 2.0.8
6:47:18 PM: ​
6:47:18 PM: ❯ Flags
6:47:18 PM:   mode: buildbot
6:47:18 PM: ​
6:47:18 PM: ❯ Current directory
6:47:18 PM:   /opt/build/repo
6:47:18 PM: ​
6:47:18 PM: ❯ Config file
6:47:18 PM:   No config file was defined: using default values.
6:47:18 PM: ​
6:47:18 PM: ❯ Context
6:47:18 PM:   production
6:47:18 PM: ​
6:47:18 PM: ❯ Loading plugins
6:47:18 PM:    - @netlify/plugin-sitemap@0.3.4 from Netlify app
6:47:18 PM:    - @netlify/plugin-lighthouse@1.1.0 from Netlify app
6:47:21 PM: ​
6:47:21 PM: ┌─────────────────────────────────────────────────────┐
6:47:21 PM: │ 1. onPostBuild command from @netlify/plugin-sitemap │
6:47:21 PM: └─────────────────────────────────────────────────────┘
6:47:21 PM: ​
6:47:21 PM: Creating sitemap from files...
6:47:21 PM: Sitemap Built! sitemap.xml
6:47:21 PM: ​
6:47:21 PM: (@netlify/plugin-sitemap onPostBuild completed in 63ms)
6:47:21 PM: ​
6:47:21 PM: ┌──────────────────────────────────────────────────────┐
6:47:21 PM: │ 2. onSuccess command from @netlify/plugin-lighthouse │
6:47:21 PM: └──────────────────────────────────────────────────────┘
6:47:21 PM: ​
6:47:21 PM: Serving and scanning site from directory /opt/build/repo
6:47:30 PM:  ⚠  warning (DeprecationWarning)  OutgoingMessage.prototype._headers is deprecated
6:47:30 PM: [DEP0066] 
6:47:30 PM:     at new module.exports (/opt/buildhome/.netlify-build-plugins/node_modules/union/lib/response-stream.js:50:60)
6:47:30 PM:     at new module.exports (/opt/buildhome/.netlify-build-plugins/node_modules/union/lib/routing-stream.js:30:17)
6:47:30 PM:     at Server.requestHandler (/opt/buildhome/.netlify-build-plugins/node_modules/union/lib/core.js:27:25)
6:47:30 PM:     at Server.emit (events.js:310:20)
6:47:30 PM:     at parserOnIncoming (_http_server.js:786:12)
6:47:30 PM:     at HTTPParser.parserOnHeadersComplete (_http_common.js:119:17)
6:48:46 PM: Error: PROTOCOL_TIMEOUT
6:48:46 PM: ​
6:48:46 PM: ┌────────────────────────────────────────────┐
6:48:46 PM: │ Plugin "@netlify/plugin-lighthouse" failed │
6:48:46 PM: └────────────────────────────────────────────┘
6:48:46 PM: ​
6:48:46 PM:   Error message
6:48:46 PM:   LHError: Failed with error: PROTOCOL_TIMEOUT
6:48:46 PM:   PROTOCOL_TIMEOUT
6:48:46 PM: ​
6:48:46 PM:   Plugin details
6:48:46 PM:   Package:        @netlify/plugin-lighthouse
6:48:46 PM:   Version:        1.1.0
6:48:46 PM:   Repository:     git+https://github.com/netlify-labs/netlify-plugin-lighthouse.git
6:48:46 PM:   npm link:       https://www.npmjs.com/package/@netlify/plugin-lighthouse
6:48:46 PM:   Report issues:  https://github.com/netlify-labs/netlify-plugin-lighthouse/issues
6:48:46 PM: ​
6:48:46 PM:   Error location
6:48:46 PM:   In "onSuccess" event in "@netlify/plugin-lighthouse" from Netlify app
6:48:46 PM:       at Timeout._onTimeout (/opt/buildhome/.netlify-build-plugins/node_modules/lighthouse/lighthouse-core/gather/driver.js:352:21)
6:48:46 PM: ​
6:48:46 PM:   Resolved config
6:48:46 PM:   build:
6:48:46 PM:     publish: /opt/build/repo
6:48:46 PM:   plugins:
6:48:46 PM:     - inputs: {}
6:48:46 PM:       origin: ui
6:48:46 PM:       package: '@netlify/plugin-sitemap'
6:48:46 PM:     - inputs: {}
6:48:46 PM:       origin: ui
6:48:46 PM:       package: '@netlify/plugin-lighthouse'
6:48:46 PM: Caching artifacts
6:48:46 PM: Started saving build plugins
6:48:46 PM: Finished saving build plugins
6:48:46 PM: Started saving pip cache
6:48:46 PM: Finished saving pip cache
6:48:46 PM: Started saving emacs cask dependencies
6:48:46 PM: Finished saving emacs cask dependencies
6:48:46 PM: Started saving maven dependencies
6:48:46 PM: Finished saving maven dependencies
6:48:46 PM: Started saving boot dependencies
6:48:46 PM: Finished saving boot dependencies
6:48:46 PM: Started saving go dependencies
6:48:46 PM: Finished saving go dependencies
6:48:46 PM: Error running command: Build script returned non-zero exit code: 1
6:48:46 PM: Failing build: Failed to build site
6:48:47 PM: Failed during stage 'building site': Build script returned non-zero exit code: 1
6:48:47 PM: Finished processing build request in 1m47.060426124s
```

[Deploy logs](https://app.netlify.com/sites/tulsihome/deploys/5ee8f78166310500074726ea).
[Bugsnag error](https://app.bugsnag.com/netlify/netlify-build/errors/5ee8f7eee9173c00180a70cd)
