### ISSUE TITLE
Deprecation warning

### ISSUE THREAD

**Issue by ehmicky** [netlify-labs/netlify-plugin-lighthouse#23]
The following deprecation warning is shown in build logs when using this plugin:

```
8:32:30 PM:  ⚠  warning (DeprecationWarning)  OutgoingMessage.prototype._headers is deprecated
8:32:30 PM: [DEP0066] 
8:32:30 PM:     at new module.exports (/opt/build/repo/.netlify/plugins/node_modules/union/lib/response-stream.js:50:60)
8:32:30 PM:     at new module.exports (/opt/build/repo/.netlify/plugins/node_modules/union/lib/routing-stream.js:30:17)
8:32:30 PM:     at Server.requestHandler (/opt/build/repo/.netlify/plugins/node_modules/union/lib/core.js:27:25)
8:32:30 PM:     at Server.emit (events.js:310:20)
8:32:30 PM:     at parserOnIncoming (_http_server.js:786:12)
8:32:30 PM:     at HTTPParser.parserOnHeadersComplete (_http_common.js:119:17)
```

Do you know what the problem might be?

**Comment by erezrokah** [comment]
Dependant of https://github.com/http-party/http-server/issues/537
